spring:
  # 应用名称
  application:
    name: wulibibiji

  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://1.117.158.138:3306/wulibbj?serverTimezone=Asia/Shanghai&characterEncoding=UTF8&autoReconnect=true&useSSL=false
    # 数据库用户名&密码
    username: root
    password: 274fb9bc570f1153
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1

  redis:
    host: 1.117.158.138
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  #邮件
  mail:
    host: smtp.163.com
    port: 465
    username: wulibibiji@163.com
    protocol: smtps
    password: PTQKUGASGYLOMKVI

# 应用服务 WEB 访问端口
server:
  port: 8081

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.yxz.wulibibiji.mybatis.entity

#日志等级
logging:
  level:
    com.yxz.wulibibiji: debug
