spring:
  # 应用名称
  application:
    name: wulibibiji

  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
    #    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master   #默认数据源
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://0.0.0.0:3307/wulibbj?serverTimezone=Asia/Shanghai&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowMultiQueries=true
          username: root
          password: 
          druid:
            # 初始连接数
            initial-size: 4
            # 最小连接池数量
            min-idle: 1
            # 最大连接池数量
            max-active: 20
            # 配置获取连接等待超时的时间
            max-wait: 60000
        slave_1:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://0.0.0.0:3307/wulibbj?serverTimezone=Asia/Shanghai&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowMultiQueries=true
          username: root
          password: 
          druid:
            # 初始连接数
            initial-size: 4
            # 最小连接池数量
            min-idle: 1
            # 最大连接池数量
            max-active: 20
            # 配置获取连接等待超时的时间
            max-wait: 60000
        slave_2:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://0.0.0.0:3307/wulibbj?serverTimezone=Asia/Shanghai&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowMultiQueries=true
          username: root
          password: 
          druid:
            # 初始连接数
            initial-size: 4
            # 最小连接池数量
            min-idle: 1
            # 最大连接池数量
            max-active: 20
            # 配置获取连接等待超时的时间
            max-wait: 60000

  #邮件
  mail:
    host: smtp.163.com
    port: 465
    username: 
    protocol: smtps
    password: 

  #文件上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  #rabbitmq配置
  rabbitmq:
    host: 0.0.0.0
    port: 5673
    username: wulibbj
    password: wulibbj
    virtualHost: /

  profiles:
    active: dev
#    active: prod

#  cloud:
#    sentinel:
#      transport:
#        port: 8082
#        dashboard: localhost:8080
#    nacos:
#      discovery:
#        server-addr: localhost:8848
  elasticsearch:
    rest:
      uris: 0.0.0.0:9200
      connection-timeout: 600

# 应用服务 WEB 访问端口
server:
  port: 8081

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis-plus:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.yxz.wulibibiji.mybatis.entity

#日志等级
logging:
  config: classpath:logback-spring.xml
  level:
    com.yxz.wulibibiji: info


#七牛配置
qiniu:
  AccessKey: 
  SecretKey: 
  Bucket: 
  cdn:
    prefix: 

sensitive:
  filename: dict.txt
